# GRC Project - SSH Hardening
# Framework: NIST 800-53 IA-2, AC-17, AC-3, AC-8
# Date: 2026-05-06

Port 2222
PermitRootLogin no
PasswordAuthentication no
PermitEmptyPasswords no
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
AllowTcpForwarding no
AllowUsers grcadmin
ClientAliveInterval 300
ClientAliveCountMax 2
Banner /etc/ssh/banner
